fix(adapter-dynamodb): update and delete session use correct partition/sort keys (#9326)
* fix(dynamodb): update/delete session use correct pk/sk

If you have defined custom options for the Dynamo adapter, such as:

```ts
  adapter: DynamoDBAdapter(client, {
    tableName: "mytable",
    partitionKey: "partitionKey",
    sortKey: "sortKey",
    indexName: "indexOnePartitionKey-indexOneSortKey-index",
    indexPartitionKey: "indexOnePartitionKey",
    indexSortKey: "indexOneSortKey",
  }),
```

The overridden values of `partitionKey` and `sortKey` are not used in `deleteSession` or `updateSession`. An error is thrown:

> ValidationException: The provided key element does not match the schema

This commit will correctly use either the default or overridden values so that these actions can be completed correctly.

* fix: ensure adapter-dynamodb tests run and pass

* fix: remove unnecessary 'as any'

---------

Co-authored-by: Nico Domino <yo@ndo.dev>